name: 'insightledger_dbt'
version: '1.0.0'
config-version: 2

profile: 'insightledger'

model-paths: [ "models" ]
test-paths: [ "tests" ]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  insightledger_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
